# Generated by Django 3.2 on 2024-10-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doctor', models.CharField(max_length=50)),
                ('apellido_doctor', models.CharField(max_length=50)),
                ('rut_doctor', models.CharField(max_length=12)),
                ('fecha_nacimiento', models.DateField()),
                ('especialidad', models.CharField(max_length=50)),
                ('correo_doctor', models.EmailField(max_length=254)),
            ],
        ),
    ]
